FROM node:12.14.1-slim AS builder
ENV APP_HOME=/app
WORKDIR $APP_HOME
# reinstall packages only when the package.json is updated
COPY ./package.json package.json
RUN npm install

COPY . .
RUN npm run build

########## prod image with nginx ##########
FROM nginx:1.19.0-alpine
ENV PROJECT_NAME=ecs-front

COPY --from=builder /app/dist/$PROJECT_NAME /app/$PROJECT_NAME
COPY --from=builder /app/config/nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
